export const GLOBAL = {
	LOADING: 'LOADING',
	SELECTORS: 'SELECTORS',
	SELECT_THREAD: 'SELECT_THREAD',
	AUTH: 'AUTH',
}

export const THREAD = {
	GET_THREAD: 'GET_THREAD',
	SORT_THREAD: 'SORT_THREAD',
	LOAD_THREAD: 'LOAD_THREAD',
	MORE_THREAD: 'MORE_THREAD',
	LOAD_SORT: 'LOAD_SORT',
	SET_T_SORT: 'SET_T_SORT',
	LOAD_T_MORE: 'LOAD_T_MORE',
	RESET_THREAD: 'RESET_THREAD',
	TP_LOAD: 'TP_LOAD',
	POST_COMMENT: 'POST_COMMENT',
	GET_MENU: 'GET_MENU',
	DESTROY_MENU: 'DESTROY_MENU',
	THREAD_ERROR: 'THREAD_ERROR'
}

export const COMMENT = {
	GET_REPLIES: 'GET_REPLIES',
	LOADING: 'LOADING',
	OPEN_REPLY: 'OPEN_REPLY',
	SHOW_MORE: 'SHOW_MORE',
	POST_REPLY: 'POST_REPLY',
	REPLY_LOADING: 'REPLY_LOADING',
	SHOW_REPLIES: 'SHOW_REPLIES',
	MORE_REPLIES: 'MORE_REPLIES',
	REPLIES_LOADING: 'REPLIES_LOADING',
	PIN: 'PIN',
	PIN_LOAD: 'PIN_LOAD',
	EDIT: 'EDIT',
	DELETE: 'DELETE',
	DELETE_LOAD: 'DELETE_LOAD',
}