export const THREAD = {
	GET_THREAD: 'GET_THREAD',
	LOAD_THREAD: 'LOAD_THREAD',
}

export const COMMENT = {
	GET_REPLIES: 'GET_REPLIES',
	LOADING: 'LOADING',
	OPEN_REPLY: 'OPEN_REPLY',
	SHOW_MORE: 'SHOW_MORE',
	POST_REPLY: 'POST_REPLY',
	REPLY_LOADING: 'REPLY_LOADING',
	SHOW_REPLIES: 'SHOW_REPLIES',
	MORE_REPLIES: 'MORE_REPLIES',
	REPLIES_LOADING: 'REPLIES_LOADING'
}